version: "2"
services:
    nacos:
        image: nacos/nacos-server:latest
        container_name: nacos
        environment:
            - MODE=standalone
        volumes:
            - /opt/nacos/logs:/home/nacos/logs
            -  /opt/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
        ports:
            - "8848:8848"